Fix compilation issue on ppc64el
Just increase the size of the buffer to make the compiler happy.

[17/70] cc -Isrc/tsm/libtsm.so.4.3.0.p -Isrc/tsm -I../src/tsm -Iexternal/wcwidth -I../external/wcwidth -Isrc/shared -I../src/shared -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=gnu99 -ffast-math -fno-strict-aliasing -ffunction-sections -fdata-sections -D_GNU_SOURCE -D_POSIX_C_SOURCE=200809L -include /<<PKGBUILDDIR>>/build/config.h -g -O3 -Werror=implicit-function-declaration -Werror=array-bounds -Werror=clobbered -Werror=volatile-register-var -ffile-prefix-map=/<<PKGBUILDDIR>>=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -fno-stack-clash-protection -fdebug-prefix-map=/<<PKGBUILDDIR>>=/usr/src/libtsm-4.3.0-2 -Wdate-time -D_FORTIFY_SOURCE=3 -fPIC -MD -MQ src/tsm/libtsm.so.4.3.0.p/tsm-vte.c.o -MF src/tsm/libtsm.so.4.3.0.p/tsm-vte.c.o.d -o src/tsm/libtsm.so.4.3.0.p/tsm-vte.c.o -c ../src/tsm/tsm-vte.c
FAILED: [code=1] src/tsm/libtsm.so.4.3.0.p/tsm-vte.c.o
cc -Isrc/tsm/libtsm.so.4.3.0.p -Isrc/tsm -I../src/tsm -Iexternal/wcwidth -I../external/wcwidth -Isrc/shared -I../src/shared -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=gnu99 -ffast-math -fno-strict-aliasing -ffunction-sections -fdata-sections -D_GNU_SOURCE -D_POSIX_C_SOURCE=200809L -include /<<PKGBUILDDIR>>/build/config.h -g -O3 -Werror=implicit-function-declaration -Werror=array-bounds -Werror=clobbered -Werror=volatile-register-var -ffile-prefix-map=/<<PKGBUILDDIR>>=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -fno-stack-clash-protection -fdebug-prefix-map=/<<PKGBUILDDIR>>=/usr/src/libtsm-4.3.0-2 -Wdate-time -D_FORTIFY_SOURCE=3 -fPIC -MD -MQ src/tsm/libtsm.so.4.3.0.p/tsm-vte.c.o -MF src/tsm/libtsm.so.4.3.0.p/tsm-vte.c.o.d -o src/tsm/libtsm.so.4.3.0.p/tsm-vte.c.o -c ../src/tsm/tsm-vte.c
../src/tsm/tsm-vte.c: In function ‘do_action’:
../src/tsm/tsm-vte.c:2092:40: error: ‘%s’ directive output may be truncated writing up to 31 bytes into a region of size 30 [-Werror=format-truncation=]
 2092 |         snprintf(buf, sizeof(buf), "\e]%s;rgb:%02x%02x/%02x%02x/%02x%02x%s",
      |                                        ^~
......
 2119 |                         vte_write_xcolor(vte, buf, end_seq, cr, cg, cb);
      |                                               ~~~
In function ‘vte_write_xcolor’,
    inlined from ‘do_osc_4’ at ../src/tsm/tsm-vte.c:2119:4,
    inlined from ‘do_osc_internal’ at ../src/tsm/tsm-vte.c:2141:3,
    inlined from ‘do_osc_end’ at ../src/tsm/tsm-vte.c:2172:6,
    inlined from ‘do_action’ at ../src/tsm/tsm-vte.c:2228:4:
../src/tsm/tsm-vte.c:2092:36: note: directive argument in the range [0, 255]
 2092 |         snprintf(buf, sizeof(buf), "\e]%s;rgb:%02x%02x/%02x%02x/%02x%02x%s",
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/tsm/tsm-vte.c:2092:36: note: directive argument in the range [0, 255]
../src/tsm/tsm-vte.c:2092:36: note: directive argument in the range [0, 255]
../src/tsm/tsm-vte.c:2092:36: note: directive argument in the range [0, 255]
../src/tsm/tsm-vte.c:2092:36: note: directive argument in the range [0, 255]
../src/tsm/tsm-vte.c:2092:36: note: directive argument in the range [0, 255]
In file included from /usr/include/stdio.h:970,
                 from ../src/tsm/tsm-vte.c:50:
In function ‘*__snprintfieee128’,
    inlined from ‘vte_write_xcolor’ at ../src/tsm/tsm-vte.c:2092:2,
    inlined from ‘do_osc_4’ at ../src/tsm/tsm-vte.c:2119:4,
    inlined from ‘do_osc_internal’ at ../src/tsm/tsm-vte.c:2141:3,
    inlined from ‘do_osc_end’ at ../src/tsm/tsm-vte.c:2172:6,
    inlined from ‘do_action’ at ../src/tsm/tsm-vte.c:2228:4:
/usr/include/powerpc64le-linux-gnu/bits/stdio2.h:68:10: note: ‘*__snprintf_chkieee128’ output between 23 and 55 bytes into a destination of size 32
   68 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   69 |                                    __glibc_objsize (__s), __fmt,
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   70 |                                    __va_arg_pack ());
      |                                    ~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
[18/70] cc -Itest/test_screen.p -Itest -I../test -Isrc/shared -I../src/shared -Isrc/tsm -I../src/tsm -Iexternal/wcwidth -I../external/wcwidth -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=gnu99 -ffast-math -fno-strict-aliasing -ffunction-sections -fdata-sections -D_GNU_SOURCE -D_POSIX_C_SOURCE=200809L -include /<<PKGBUILDDIR>>/build/config.h -g -O3 -Werror=implicit-function-declaration -Werror=array-bounds -Werror=clobbered -Werror=volatile-register-var -ffile-prefix-map=/<<PKGBUILDDIR>>=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -fno-stack-clash-protection -fdebug-prefix-map=/<<PKGBUILDDIR>>=/usr/src/libtsm-4.3.0-2 -Wdate-time -D_FORTIFY_SOURCE=3 -pthread -MD -MQ test/test_screen.p/.._src_tsm_tsm-selection.c.o -MF test/test_screen.p/.._src_tsm_tsm-selection.c.o.d -o test/test_screen.p/.._src_tsm_tsm-selection.c.o -c ../src/tsm/tsm-selection.c
[19/70] cc -Itest/test_screen.p -Itest -I../test -Isrc/shared -I../src/shared -Isrc/tsm -I../src/tsm -Iexternal/wcwidth -I../external/wcwidth -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=gnu99 -ffast-math -fno-strict-aliasing -ffunction-sections -fdata-sections -D_GNU_SOURCE -D_POSIX_C_SOURCE=200809L -include /<<PKGBUILDDIR>>/build/config.h -g -O3 -Werror=implicit-function-declaration -Werror=array-bounds -Werror=clobbered -Werror=volatile-register-var -ffile-prefix-map=/<<PKGBUILDDIR>>=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -fno-stack-clash-protection -fdebug-prefix-map=/<<PKGBUILDDIR>>=/usr/src/libtsm-4.3.0-2 -Wdate-time -D_FORTIFY_SOURCE=3 -pthread -MD -MQ test/test_screen.p/.._src_tsm_tsm-unicode.c.o -MF test/test_screen.p/.._src_tsm_tsm-unicode.c.o.d -o test/test_screen.p/.._src_tsm_tsm-unicode.c.o -c ../src/tsm/tsm-unicode.c
[20/70] cc -Itest/test_screen.p -Itest -I../test -Isrc/shared -I../src/shared -Isrc/tsm -I../src/tsm -Iexternal/wcwidth -I../external/wcwidth -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=gnu99 -ffast-math -fno-strict-aliasing -ffunction-sections -fdata-sections -D_GNU_SOURCE -D_POSIX_C_SOURCE=200809L -include /<<PKGBUILDDIR>>/build/config.h -g -O3 -Werror=implicit-function-declaration -Werror=array-bounds -Werror=clobbered -Werror=volatile-register-var -ffile-prefix-map=/<<PKGBUILDDIR>>=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -fno-stack-clash-protection -fdebug-prefix-map=/<<PKGBUILDDIR>>=/usr/src/libtsm-4.3.0-2 -Wdate-time -D_FORTIFY_SOURCE=3 -pthread -MD -MQ test/test_screen.p/.._src_tsm_tsm-screen.c.o -MF test/test_screen.p/.._src_tsm_tsm-screen.c.o.d -o test/test_screen.p/.._src_tsm_tsm-screen.c.o -c ../src/tsm/tsm-screen.c
ninja: build stopped: subcommand failed.
dh_auto_build: error: cd build && LC_ALL=C.UTF-8 ninja -j4 -v returned exit code 1
make: *** [debian/rules:12: binary-arch] Error 25

Signed-off-by: Jocelyn Falempe <jfalempe@redhat.com>